# Generated by Django 3.0.4 on 2020-03-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsEstimation',
            fields=[
                ('age_limit', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('estimation', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'contacts_estimation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icd_10_code', models.CharField(blank=True, max_length=5, null=True)),
                ('sar_estimation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disease',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiseaseSeason',
            fields=[
                ('disease_season_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.Disease')),
            ],
            options={
                'db_table': 'disease_season',
                'managed': True,
                'unique_together': {('disease', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='InternalsDataHandlingTask',
            fields=[
                ('internals_data_handling_task_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50, unique=True)),
                ('frequency_days', models.IntegerField()),
                ('last_update', models.DateField(blank=True, null=True)),
                ('enabled_flag', models.BooleanField()),
                ('command_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'internals_data_handling_task',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PopulationStats',
            fields=[
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='analyzer.Country')),
                ('year', models.IntegerField()),
                ('population', models.BigIntegerField()),
            ],
            options={
                'db_table': 'population_stats',
                'managed': True,
                'unique_together': {('country', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DiseaseStats',
            fields=[
                ('disease_stats_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stats_date', models.DateField()),
                ('confirmed', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('disease_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.DiseaseSeason')),
            ],
            options={
                'db_table': 'disease_stats',
                'managed': True,
                'unique_together': {('disease_season', 'stats_date')},
            },
        ),
        migrations.CreateModel(
            name='AgeGroupCfr',
            fields=[
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='analyzer.Disease')),
                ('age_limit', models.SmallIntegerField()),
                ('cfr', models.FloatField()),
            ],
            options={
                'db_table': 'age_group_cfr',
                'managed': True,
                'unique_together': {('disease', 'age_limit')},
            },
        ),
        migrations.CreateModel(
            name='ComorbidConditionCfr',
            fields=[
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='analyzer.Disease')),
                ('cfr', models.FloatField()),
                ('comorbid_disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='analyzer.Disease')),
            ],
            options={
                'db_table': 'comorbid_condition_cfr',
                'managed': True,
                'unique_together': {('disease', 'comorbid_disease')},
            },
        ),
    ]
