# Generated by Django 3.0.4 on 2020-03-24 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroupcfr',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='analyzer.Disease'),
        ),
        migrations.AlterField(
            model_name='comorbidconditioncfr',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='analyzer.Disease'),
        ),
        migrations.AlterField(
            model_name='populationstats',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='analyzer.Country'),
        ),
    ]
