# Generated by Django 3.0.4 on 2020-03-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20200324_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroupcfr',
            name='age_group_cfr_id',
            field=models.AutoField(default=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comorbidconditioncfr',
            name='comorbid_condition_cfr_id',
            field=models.AutoField(default=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='populationstats',
            name='population_stats_id',
            field=models.AutoField(default=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agegroupcfr',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.Disease'),
        ),
        migrations.AlterField(
            model_name='comorbidconditioncfr',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.Disease'),
        ),
        migrations.AlterField(
            model_name='populationstats',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.Country'),
        ),
    ]
