# Generated by Django 3.0.4 on 2020-03-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_auto_20200324_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasestats',
            name='recovered',
            field=models.IntegerField(null=True),
        ),
    ]
