# Generated by Django 3.0.4 on 2020-04-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_auto_20200329_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseStats',
            fields=[
                ('bed_stats_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('nurses_per_k', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.Country')),
            ],
            options={
                'db_table': 'nurse_stats',
                'managed': True,
                'unique_together': {('country', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BedStats',
            fields=[
                ('bed_stats_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('beds_per_k', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.Country')),
            ],
            options={
                'db_table': 'bed_stats',
                'managed': True,
                'unique_together': {('country', 'year')},
            },
        ),
    ]
