# Generated by Django 3.0.4 on 2020-04-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_bedstats_nursestats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursestats',
            old_name='bed_stats_id',
            new_name='nurse_stats_id',
        ),
    ]
